version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nutrisipe-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nutrisipe
      POSTGRES_PASSWORD: nutrisipe
      POSTGRES_DB: nutrisipe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
